name: Adrian Walsh
favicon: null
layout_spectrum: 0.32391586201265454
typography_spectrum: 0.27525693248026073
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9060485293157399
  lightness: 0.9116040533408523
  saturation: 0.2273550326935947
  rhythmicContrast: 0.20358295598998666
purpose: []
